from . import MIT, UNLICENSE, APACHE_2, GPL_3, BSD_2, BSD_3, LGPL_2, LGPL_3

# A mapping to the different license templates.
LICENSES = {
    'APACHE-2': APACHE_2.TEMPLATE,
    'GPL-3': GPL_3.TEMPLATE,
    'BSD-2': BSD_2.TEMPLATE,
    'BSD-3': BSD_3.TEMPLATE,
    'LGPL-2': LGPL_2.TEMPLATE,
    'LGPL-3': LGPL_3.TEMPLATE,
    'MIT': MIT.TEMPLATE,
    'UNLICENSE': UNLICENSE.TEMPLATE,
}
